const fs = require('fs');
let html = fs.readFileSync('index.html', 'utf8');

const startString = '<div class="all-tools-section" id="allToolsSection">';
const endString = '<div id="about-page" class="page-view" style="display: none;">';

const startIndex = html.indexOf(startString);
const endIndex = html.indexOf(endString);

if (startIndex !== -1 && endIndex !== -1) {
    const replacement = `<div class="all-tools-section" id="allToolsSection">
                <h2 class="section-heading">All Tools Explorer</h2>
                <!-- Back Button (Hidden by default) -->
                <div class="back-button-container" id="backButtonContainer" style="display: none;">
                    <button class="back-button premium-back" id="backButton">&larr; Back to Categories</button>
                    <h2 id="currentFolderTitle" class="current-folder-title"></h2>
                </div>

                <!-- Folders Grid -->
                <div class="tools-container premium-tools-container" id="toolsContainer">
                    <div class="folders-grid" id="foldersGrid">
                        <!-- Folder cards will be generated by JavaScript -->
                    </div>
                    
                    <!-- Tools Grid (Hidden until folder is clicked) -->
                    <div class="tools-grid" id="toolsGrid" style="display: none;">
                        <!-- Tool squares will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Infinity Kit Ecosystem Bento Grid -->
            <section class="why-choose-section" style="padding-top: 80px; padding-bottom: 80px;">
                <h2 class="section-heading" style="text-align: center; margin-bottom: 50px;">The Infinity Ecosystem</h2>
                
                <div class="bento-grid">
                    <!-- Big Box 1: Functions -->
                    <div class="bento-card large-card scroll-reveal">
                        <div class="bento-content">
                            <h3>50+ Powerful Functions</h3>
                            <p>From complex PDF manipulation to advanced financial tracking and data conversion. Everything you need is right here, running natively in your browser.</p>
                            <a href="#" onclick="document.querySelector('.all-tools-section').scrollIntoView({behavior: 'smooth'})" class="read-more" style="color: #0145F2; margin-top: 20px; display: inline-block; font-weight: 600;">Explore all functions &rarr;</a>
                        </div>
                        <div class="bento-visual functions-visual"></div>
                    </div>
                    
                    <!-- Box 2: Developers -->
                    <div class="bento-card scroll-reveal">
                        <div class="bento-content">
                            <h3>Developer Ready</h3>
                            <p>Regex testers, URL encoders, JSON validators, and advanced formatting tools. Built for developers, by developers.</p>
                        </div>
                    </div>

                    <!-- Box 3: Performance -->
                    <div class="bento-card scroll-reveal" style="background: linear-gradient(135deg, #0145F2 0%, #013bc7 100%); color: white;">
                        <div class="bento-content">
                            <h3 style="color: white;">Lightning Fast</h3>
                            <p style="color: rgba(255,255,255,0.8);">No heavy loading times. All utilities are highly optimized for instant execution without delays.</p>
                        </div>
                    </div>

                    <!-- Box 4: Wide Feature -->
                    <div class="bento-card wide-card scroll-reveal">
                        <div class="bento-content">
                            <h3>Secure Cloud Synchronization</h3>
                            <p>Your history, favorites, and settings are securely synchronized across all your devices, giving you a continuous workflow whether on desktop or mobile.</p>
                        </div>
                    </div>

                    <!-- Box 5: Design -->
                    <div class="bento-card scroll-reveal">
                        <div class="bento-content">
                            <h3>Premium Design</h3>
                            <p>Enjoy a beautiful, minimal, distraction-free environment while you work.</p>
                        </div>
                    </div>
                </div>
            </section>

            <!-- Blog Section -->
            <section class="blog-section">
                <h2 class="section-heading">Latest Insights</h2>
                <div class="blog-grid" id="homeUpdatesContainer">
                    <div style="text-align: center; width: 100%; opacity: 0.7; padding: 40px 0;">Loading latest updates...</div>
                </div>
            </section>

        </div> <!-- End Home Page View -->

        <!-- About Page View -->
        `;
    
    html = html.substring(0, startIndex) + replacement + html.substring(endIndex);
    fs.writeFileSync('index.html', html);
    console.log("Successfully rebuilt the section.");
} else {
    console.log("Could not find start or end tags.");
}
