'use client';

import React, { useState, useRef } from 'react';
import { Upload, Copy, Check, Download, Eye, FileCode, AlertCircle } from 'lucide-react';

interface OptimizeOptions {
  removeComments: boolean;
  removeMetadata: boolean;
  collapseWhitespace: boolean;
  removeEmptyAttrs: boolean;
  roundDecimals: boolean;
  decimalPlaces: number;
}

function optimizeSVG(svg: string, opts: OptimizeOptions): string {
  let result = svg;

  // Remove XML declaration
  result = result.replace(/<\?xml[^?]*\?>/g, '');

  // Remove comments
  if (opts.removeComments) {
    result = result.replace(/<!--[\s\S]*?-->/g, '');
  }

  // Remove metadata tags
  if (opts.removeMetadata) {
    result = result.replace(/<metadata[\s\S]*?<\/metadata>/gi, '');
    result = result.replace(/<title[\s\S]*?<\/title>/gi, '');
    result = result.replace(/<desc[\s\S]*?<\/desc>/gi, '');
    result = result.replace(/<rdf:RDF[\s\S]*?<\/rdf:RDF>/gi, '');
  }

  // Round decimal places
  if (opts.roundDecimals) {
    const factor = Math.pow(10, opts.decimalPlaces);
    result = result.replace(/-?\d+\.\d+/g, (match) => {
      return String(Math.round(Number(match) * factor) / factor);
    });
  }

  // Remove empty attributes
  if (opts.removeEmptyAttrs) {
    result = result.replace(/\s+\w+=""/g, '');
    result = result.replace(/\s+\w+='' /g, ' ');
  }

  // Remove style attributes that are just whitespace or defaults
  if (opts.removeEmptyAttrs) {
    result = result.replace(/\s+style="\s*"/g, '');
    result = result.replace(/\s+class="\s*"/g, '');
  }

  // Collapse whitespace
  if (opts.collapseWhitespace) {
    // Collapse multiple spaces/tabs/newlines into a single space, but keep structure
    result = result
      .replace(/\n\s*/g, '')        // Remove newlines + leading whitespace
      .replace(/\s{2,}/g, ' ')      // Multiple spaces → single space
      .replace(/>\s+</g, '><')      // Remove whitespace between tags
      .replace(/\s+\/>/g, '/>')     // Normalize self-closing tags
      .trim();
  } else {
    result = result.trim();
  }

  return result;
}

const SAMPLE_SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Illustrator -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <metadata>
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description>Sample SVG</rdf:Description>
    </rdf:RDF>
  </metadata>
  <title>Circle Icon</title>
  <desc>A simple circle</desc>

  <!-- Main circle -->
  <circle cx="50.0000" cy="50.0000" r="40.0000" fill="#6366f1" stroke="#4f46e5" stroke-width="2.0000" />

  <!-- Star shape -->
  <polygon points="50.0000,20.0000 61.8034,41.7082 86.6025,45.4508 68.3013,63.2918 72.6543,88.0000 50.0000,76.0000 27.3457,88.0000 31.6987,63.2918 13.3975,45.4508 38.1966,41.7082" fill="#fbbf24" style="" class="" />
</svg>`;

export default function SVGOptimizer() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);
  const [opts, setOpts] = useState<OptimizeOptions>({
    removeComments: true,
    removeMetadata: true,
    collapseWhitespace: true,
    removeEmptyAttrs: true,
    roundDecimals: true,
    decimalPlaces: 2,
  });
  const [previewTab, setPreviewTab] = useState<'original' | 'optimized'>('original');
  const [error, setError] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);

  const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => {
      const text = ev.target?.result as string;
      setInput(text);
      setOutput('');
      setError('');
    };
    reader.readAsText(file);
  };

  const handleOptimize = () => {
    const src = input.trim();
    if (!src) { setError('Please paste or upload an SVG first.'); return; }
    if (!src.includes('<svg')) { setError('Input does not appear to be valid SVG markup.'); return; }
    setError('');
    try {
      const result = optimizeSVG(src, opts);
      setOutput(result);
    } catch (err) {
      setError('Optimization failed. Please check your SVG.');
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([output], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `optimized_${Date.now()}.svg`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const OrigBytes = new TextEncoder().encode(input).length;
  const OptBytes = new TextEncoder().encode(output).length;
  const reduction = OrigBytes > 0 && OptBytes > 0 ? (((OrigBytes - OptBytes) / OrigBytes) * 100).toFixed(1) : null;

  const CheckOpt = ({ label, field }: { label: string; field: keyof OptimizeOptions }) => (
    <label style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', padding: '8px 0', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
      <input
        type="checkbox"
        checked={opts[field] as boolean}
        onChange={e => setOpts(prev => ({ ...prev, [field]: e.target.checked }))}
        style={{ accentColor: 'var(--primary-color)', width: '16px', height: '16px', cursor: 'pointer' }}
      />
      <span style={{ fontSize: '0.85rem' }}>{label}</span>
    </label>
  );

  return (
    <div style={{ padding: '10px 0' }}>
      <div className="glass-panel" style={{ maxWidth: '1050px', margin: '0 auto' }}>
        <h2 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '1.8rem', fontWeight: 800, marginBottom: '8px' }}>
          SVG Optimizer & Minifier
        </h2>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginBottom: '26px' }}>
          Strip bloat from SVG markup and reduce file size without losing visual quality.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '22px' }}>
          {/* Left: Input + Options */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {/* Input area */}
            <div className="glass-panel" style={{ margin: 0, padding: '18px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px', flexWrap: 'wrap', gap: '8px' }}>
                <h3 style={{ fontSize: '0.95rem', fontWeight: 700, margin: 0 }}>SVG Input</h3>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <button className="btn btn-secondary" style={{ fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '5px' }} onClick={() => fileRef.current?.click()}>
                    <Upload size={13} /> Upload .svg
                  </button>
                  <button className="btn btn-secondary" style={{ fontSize: '0.75rem' }} onClick={() => { setInput(SAMPLE_SVG); setOutput(''); setError(''); }}>
                    Load Sample
                  </button>
                  <input ref={fileRef} type="file" accept=".svg,image/svg+xml" style={{ display: 'none' }} onChange={handleFile} />
                </div>
              </div>
              <textarea
                value={input}
                onChange={e => { setInput(e.target.value); setOutput(''); setError(''); }}
                className="form-textarea"
                placeholder="Paste SVG code here..."
                style={{ width: '100%', minHeight: '180px', fontFamily: 'monospace', fontSize: '0.8rem', background: 'rgba(0,0,0,0.15)', border: '1px solid var(--glass-border)', resize: 'vertical' }}
              />
              {OrigBytes > 0 && (
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: '6px' }}>
                  Original size: <strong>{(OrigBytes / 1024).toFixed(2)} KB</strong> ({OrigBytes} bytes)
                </p>
              )}
            </div>

            {/* Options */}
            <div className="glass-panel" style={{ margin: 0, padding: '18px' }}>
              <h3 style={{ fontSize: '0.95rem', fontWeight: 700, marginBottom: '14px' }}>Optimization Options</h3>
              <CheckOpt label="Remove HTML comments" field="removeComments" />
              <CheckOpt label="Remove metadata, title & desc" field="removeMetadata" />
              <CheckOpt label="Collapse whitespace & newlines" field="collapseWhitespace" />
              <CheckOpt label="Remove empty attributes" field="removeEmptyAttrs" />
              <CheckOpt label="Round decimal places" field="roundDecimals" />

              {opts.roundDecimals && (
                <div style={{ paddingTop: '12px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <label style={{ fontSize: '0.83rem', color: 'var(--text-secondary)', fontWeight: 600 }}>Decimal Places</label>
                    <strong style={{ color: 'var(--primary-color)' }}>{opts.decimalPlaces}</strong>
                  </div>
                  <input
                    type="range"
                    min={0}
                    max={5}
                    value={opts.decimalPlaces}
                    onChange={e => setOpts(prev => ({ ...prev, decimalPlaces: Number(e.target.value) }))}
                    style={{ width: '100%', accentColor: 'var(--primary-color)' }}
                  />
                </div>
              )}

              <button className="btn" style={{ width: '100%', marginTop: '16px', fontSize: '0.9rem' }} onClick={handleOptimize}>
                <FileCode size={15} style={{ marginRight: '6px', display: 'inline-block', verticalAlign: 'middle' }} />
                Optimize SVG
              </button>
            </div>
          </div>

          {/* Right: Output + Preview */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {/* Size stats */}
            {reduction && (
              <div style={{
                display: 'grid',
                gridTemplateColumns: '1fr 1fr 1fr',
                gap: '10px',
              }}>
                {[
                  { label: 'Original', value: `${(OrigBytes / 1024).toFixed(2)} KB`, sub: `${OrigBytes}B`, color: '#888' },
                  { label: 'Optimized', value: `${(OptBytes / 1024).toFixed(2)} KB`, sub: `${OptBytes}B`, color: '#28a745' },
                  { label: 'Saved', value: `${reduction}%`, sub: `${OrigBytes - OptBytes}B`, color: 'var(--primary-color)' },
                ].map((s, i) => (
                  <div key={i} style={{ background: 'rgba(255,255,255,0.04)', borderRadius: '12px', padding: '12px 14px', textAlign: 'center', border: '1px solid var(--glass-border)' }}>
                    <div style={{ fontSize: '0.72rem', color: 'var(--text-secondary)', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{s.label}</div>
                    <div style={{ fontSize: '1.1rem', fontWeight: 800, color: s.color }}>{s.value}</div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>{s.sub}</div>
                  </div>
                ))}
              </div>
            )}

            {error && (
              <div style={{ background: 'rgba(220,53,69,0.1)', border: '1px solid rgba(220,53,69,0.25)', borderRadius: '10px', padding: '10px 14px', color: '#e05565', fontSize: '0.84rem', display: 'flex', gap: '8px', alignItems: 'center' }}>
                <AlertCircle size={15} /> {error}
              </div>
            )}

            {/* Output */}
            <div className="glass-panel" style={{ margin: 0, padding: '18px', flex: 1 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px', flexWrap: 'wrap', gap: '8px' }}>
                <h3 style={{ fontSize: '0.95rem', fontWeight: 700, margin: 0 }}>Optimized SVG</h3>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <button className="btn btn-secondary" style={{ fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '5px' }} onClick={handleCopy} disabled={!output}>
                    {copied ? <Check size={13} color="#28a745" /> : <Copy size={13} />} Copy
                  </button>
                  <button className="btn btn-secondary" style={{ fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '5px' }} onClick={handleDownload} disabled={!output}>
                    <Download size={13} /> .svg
                  </button>
                </div>
              </div>
              <textarea
                readOnly
                value={output || 'Optimized SVG will appear here...'}
                className="form-textarea"
                style={{ width: '100%', minHeight: '160px', fontFamily: 'monospace', fontSize: '0.8rem', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--glass-border)', color: output ? 'var(--text-color)' : 'var(--text-secondary)', resize: 'vertical' }}
              />
            </div>

            {/* SVG Preview */}
            <div className="glass-panel" style={{ margin: 0, padding: '18px' }}>
              <div style={{ display: 'flex', gap: '6px', marginBottom: '14px', background: 'rgba(255,255,255,0.03)', borderRadius: '10px', padding: '4px', width: 'fit-content' }}>
                {(['original', 'optimized'] as const).map(tab => (
                  <button
                    key={tab}
                    onClick={() => setPreviewTab(tab)}
                    className={`btn ${previewTab === tab ? '' : 'btn-secondary'}`}
                    style={{ fontSize: '0.75rem', padding: '5px 12px', textTransform: 'capitalize', border: 'none' }}
                  >
                    <Eye size={12} style={{ display: 'inline', verticalAlign: 'middle', marginRight: '4px' }} />
                    {tab}
                  </button>
                ))}
              </div>
              <div style={{
                background: 'rgba(255,255,255,0.04)',
                borderRadius: '12px',
                padding: '20px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                minHeight: '120px',
                border: '1px solid var(--glass-border)',
              }}>
                {(previewTab === 'original' ? input : output) ? (
                  <div
                    dangerouslySetInnerHTML={{ __html: previewTab === 'original' ? input : output }}
                    style={{ maxWidth: '120px', maxHeight: '120px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                  />
                ) : (
                  <span style={{ color: 'var(--text-secondary)', fontSize: '0.84rem' }}>
                    {previewTab === 'original' ? 'Paste SVG to preview' : 'Optimize SVG to preview'}
                  </span>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
