'use client';

import React from 'react';
import { AlertCircle, FileText, ExternalLink, HardDrive } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div style={{ maxWidth: '850px', margin: '80px auto 40px', padding: '40px 20px' }}>
      
      {/* Header */}
      <header style={{ textAlign: 'center', marginBottom: '40px' }}>
        <h1 style={{
          fontFamily: "'Outfit', sans-serif",
          fontSize: '2.5rem',
          fontWeight: 800,
          color: 'var(--text-color)',
          marginBottom: '10px'
        }}>
          Disclaimer
        </h1>
        <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
          Last Updated: May 8, 2026
        </p>
      </header>

      {/* Main Glass Panel */}
      <div className="glass-panel" style={{
        padding: '45px',
        background: 'var(--glass-bg)',
        border: '1px solid var(--glass-border)',
        borderRadius: 'var(--card-radius)',
        boxShadow: '0 8px 32px rgba(31, 38, 135, 0.04)',
        display: 'flex',
        flexDirection: 'column',
        gap: '35px'
      }}>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
          <h2 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '1.5rem', fontWeight: 700, color: 'var(--primary-color)', margin: 0, display: 'flex', alignItems: 'center', gap: '10px' }}>
            <FileText size={22} /> General Information
          </h2>
          <p style={{ fontSize: '1.05rem', lineHeight: '1.7', color: 'var(--text-color)', margin: 0, opacity: 0.95 }}>
            The web calculators, text builders, translators, conversions, and AI engines available on Infinity Kit are provided exclusively for general informational and utility purposes. While our engineering team works diligently to preserve peak execution speeds and correct mathematical models, we make no representations or warranties of any kind regarding the completeness, accuracy, or suitability of the outputs.
          </p>
        </section>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
          <h2 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '1.5rem', fontWeight: 700, color: 'var(--primary-color)', margin: 0, display: 'flex', alignItems: 'center', gap: '10px' }}>
            <AlertCircle size={22} /> No Professional Advice
          </h2>
          <p style={{ fontSize: '1.05rem', lineHeight: '1.7', color: 'var(--text-color)', margin: 0, opacity: 0.95 }}>
            The calculated results generated by our tool catalog (including health calculators, expense suites, loan ratios, or unit systems) do not constitute medical, financial, legal, or structural professional advice. Reliance on these metrics is strictly at your own risk. You should always consult with a licensed doctor, certified financial advisor, or legal advocate prior to making critical decisions.
          </p>
        </section>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
          <h2 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '1.5rem', fontWeight: 700, color: 'var(--primary-color)', margin: 0, display: 'flex', alignItems: 'center', gap: '10px' }}>
            <ExternalLink size={22} /> External Hyperlinks
          </h2>
          <p style={{ fontSize: '1.05rem', lineHeight: '1.7', color: 'var(--text-color)', margin: 0, opacity: 0.95 }}>
            Infinity Kit may contain links leading to external web resources managed by third-party providers. We have absolutely no control over the nature, correctness, availability, or tracking behaviors of those external domains. The inclusion of these links does not imply an endorsement of the views expressed in their pages.
          </p>
        </section>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
          <h2 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '1.5rem', fontWeight: 700, color: 'var(--primary-color)', margin: 0, display: 'flex', alignItems: 'center', gap: '10px' }}>
            <HardDrive size={22} /> Technical Boundaries
          </h2>
          <p style={{ fontSize: '1.05rem', lineHeight: '1.7', color: 'var(--text-color)', margin: 0, opacity: 0.95 }}>
            We maintain no responsibility or liabilities regarding temporary browser lags, client-side data loss, or browser settings mismatch resulting from interactions with our site scripts. The utilities are tailored to operate on modern standard browsers and might render with reduced features on legacy internet platforms.
          </p>
        </section>

      </div>

    </div>
  );
}
